### ISSUE TITLE
Datenstrukturen anlegen + Anbindung an Gerätespeicher

### ISSUE THREAD

**Issue by HDingeldein** [SG-P13/abi-quiz#8]
Erstellen der Datenstrukturen für Spielerprofil, Fragen, Katalog sodass sie als JSON gespeichert werden können.
Katalog sollte eine Liste vom Datentyp Frage enthalten

Entwurf/ Vorschlag:

![Image](https://github.com/SG-P13/abi-quiz/assets/113993544/65420784-4944-440a-b45e-f252f0920ca5)

**Comment by HDingeldein** [comment]
Akzeptanzkriterium: Speichern von Fragen(-katalogen) im Gerätespeicher + Laden soll möglich sein

**Comment by dmc1011** [comment]
Vorschlag: eigene Structs für das Modellieren von Antworten

z.B. "Answer" enthält zwei Objekte "TextItem" (String) und "ImageItem" (irgendein Bildformat), darüber hinaus noch Metadaten (ID, isCorrectAnswer (bool), ... und was sonst noch nötig sein könnte) und das Struct "Question" erhält dann ein Attribut vom Typ Answer-Array mit Größe 4, worin die einzelnen Antworten abgelegt sind.

Außerdem kam die Idee auf das Attribut "ImageOrText" des Question Structs aufzuspalten in ein "TextItem" und ein "ImageItem". Das hätte den Vorteil, dass eine Frage beides enthalten könnte und die Logik getrennt ist.

**Comment by HDingeldein** [comment]
Verstehe ich das so in etwa richtig?
Question:
id
questionText
questionImage
(correctAnswerIndex)
List<Answer> answers

Answer:
id
isCorrectAnswer
text
image

Finde ich eine gute Idee, das können wir so machen. Gleiches gilt für die Trennung von Image und Text Item. Wobei ich es in diesem issue erstmal darauf beschränken würde, dass das mit Text einwandfrei funktioniert und dann z.B. in der nächsten Woche/ Iteration das mit den Bildern hinzufügen

**Comment by dmc1011** [comment]
Ja genau, alles was mit Bildern zu tun hat kann man erstmal als leere hülle lassen und in den nächsten Wochen mit Funktionalität füllen
