### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by dmc1011** [SG-P13/abi-quiz#86]

**Comment by MarcusTU** [comment]
- In jedem Screen den Canvas von: "Screen Space - Overlay" in "Screen Space - Camera" ändern.
- In jedem Screen werden dadurch alle sachen die "nicht" Scale/Aspect invariant waren nicht mehr funktionieren
- Das muss dann alles gefixt werden. Danach sollte es gehen.

**Comment by MarcusTU** [comment]
Den HexBackground könnt ihr erstmal ignorieren (falls hier jemand etwas macht), ich kümmere mich darum, sobald es soweit ist.
